# docker-compose.yml para o pgAdmin

services:
  pgadmin: # Nome do serviço para o contêiner pgAdmin
    image: dpage/pgadmin4:latest # Imagem Docker oficial do pgAdmin
    container_name: foninhoiuri-pgadmin # Nome amigável para o contêiner
    restart: unless-stopped
    # user: "1000:1000" # REMOVIDO
    ports:
      - "5051:5051" # Mapeia a porta 5051 do HOST para a porta 5051 do contêiner
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com # Altamente recomendado mudar!
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword # Altamente recomendado mudar!
      PGADMIN_LISTEN_PORT: 5051 # Porta que o pgAdmin escuta internamente
      PGADMIN_SETUP_WEB: "false"
      PGADMIN_SETUP_EXPERT_MODE: "true"
      # UID e GID esperados pelo usuário interno 'pgadmin' na imagem Docker
      PGADMIN_UID: "5050" # <--- ADICIONADO: UID do usuário 'pgadmin' na imagem
      PGADMIN_GID: "5050" # <--- ADICIONADO: GID do grupo 'pgadmin' na imagem
    volumes:
      - ${APP_DATA_DIR}/data/pgadmin_data:/var/lib/pgadmin
      - ${APP_DATA_DIR}/data/pgadmin_data/sessions:/var/lib/pgadmin/sessions
      - ${APP_DATA_DIR}/data/pgadmin_data/storage:/var/lib/pgadmin/storage
      - ${APP_DATA_DIR}/data/pgadmin_logs:/var/log/pgadmin # Volume para logs
