# docker-compose.yml para o pgAdmin

services:
  pgadmin: # Nome do serviço para o contêiner pgAdmin
    image: dpage/pgadmin4:latest # Imagem Docker oficial do pgAdmin
    container_name: foninhoiuri-pgadmin # Nome amigável para o contêiner
    restart: unless-stopped
    user: "1000:1000" # Executar o contêiner como o usuário Umbrel (UID 1000, GID 1000)
    ports:
      - "5051:5051" # <--- ALTERADO: Mapeia a porta 5051 do HOST para a porta 5051 do contêiner
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com # Altamente recomendado mudar!
      PGADMIN_DEFAULT_PASSWORD: supersecretpassword # Altamente recomendado mudar!
      PGADMIN_LISTEN_PORT: 5051 # <--- ALTERADO: Porta que o pgAdmin escuta internamente
      PGADMIN_SETUP_WEB: "false"
      PGADMIN_SETUP_EXPERT_MODE: "true"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/pgadmin # Persistência de dados do pgAdmin (configurações, históricos)
