version: "3.7"

services:
  ngrok:
    image: Foninhoiuri/docker-ngrok:latest
    container_name: foninhoiuri-ngrok
    depends_on:
      - web
    ports:
      - "4551:4551"      # Interface web do ngrok (HTTP Inspector)
    environment:
      # Seu token obtido em https://dashboard.ngrok.com/auth
      NGROK_AUTH_TOKEN: ${NGROK_AUTH_TOKEN}
      # Região do túnel (us, eu, ap, au, sa, jp, in)
      REGION: us
      # Nome do serviço Docker que será exposto (é o hostname)
      DOMAIN: web
      # Porta interna do serviço web que o ngrok deve encaminhar
      PORT: 5678
      # Ativa logs de debug no terminal (opcional)
      DEBUG: "true"
