services:
  ngrok:
    image: ngrok/ngrok:main
    container_name: foninhoiuri-ngrok
    network_mode: "host"  # ngrok vai enxergar localhost:8080
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}  # defina em .env ou na UI do Umbrel
    command: http 8080
