# foninhoiuri-kong/docker-compose.yml
version: '3.8'

services:
  kong-database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD:-kong} # Você pode definir KONG_DB_PASSWORD no seu .env ou deixar o padrão
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong -d kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço para executar as migrações do Kong com um pequeno atraso
  kong-migrations:
    image: kong:latest
    # Adicionando um atraso de 10 segundos antes de rodar o comando de migração
    command: ["sh", "-c", "sleep 10 && kong migrations bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_DATABASE: kong
    depends_on:
      kong-database:
        condition: service_healthy
    restart: "no" # Garante que este serviço roda apenas uma vez com sucesso

  kong:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migrations: # O Kong agora depende do serviço de migrações
        condition: service_completed_successfully # Garante que as migrações terminaram com sucesso
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "8000:8000/tcp" # Porta do proxy HTTP
      - "8443:8443/tcp" # Porta do proxy HTTPS
      - "8001:8001/tcp" # Porta da API Admin HTTP
      - "8444:8444/tcp" # Porta da API Admin HTTPS
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kong_data:
