# foninhoiuri-kong/docker-compose.yml
version: '3.8'

services:
  # O serviço 'kong-database' foi removido, pois o Kong usará um PostgreSQL existente.
  # O serviço 'db-setup' também foi removido conforme sua solicitação.
  #
  # ATENÇÃO MUITO IMPORTANTE:
  # O banco de dados 'kong' DEVE ser criado manualmente no seu PostgreSQL existente.
  # Conecte-se ao seu PostgreSQL (host: postgresql, user: default, password: default)
  # e execute o comando SQL: CREATE DATABASE kong;
  # Se você não fizer isso, a instalação do Kong FALHARÁ!

  # Serviço para executar as migrações do Kong
  kong-migrations:
    image: kong:latest
    command: ["sh", "-c", "sleep 10 && kong migrations bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql # DEFINITIVO: Nome do contêiner PostgreSQL existente
      KONG_PG_USER: default   # DEFINITIVO: Usuário 'default'
      KONG_PG_PASSWORD: default # DEFINITIVO: Senha 'default'
      KONG_PG_DATABASE: kong
      TZ: America/Sao_Paulo
    restart: "no"
  kong:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      kong-migrations: # O Kong principal só inicia após as migrações terem sido concluídas
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql # DEFINITIVO: Nome do contêiner PostgreSQL existente
      KONG_PG_USER: default   # DEFINITIVO: Usuário 'default'
      KONG_PG_PASSWORD: default # DEFINITIVO: Senha 'default'
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000,0.0.0.0:8443 ssl
      TZ: America/Sao_Paulo
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # Volume para dados gerais do aplicativo Kong (não dados do banco de dados)
      # Isso cria uma pasta 'data/foninhoiuri-kong/app_data' no seu Umbrel para persistir esses dados.
      - ${APP_DATA_DIR}/data:/usr/local/kong/prefix/

app_proxy:
  - frontend: 8000
    backend: 8000
  - frontend: 8443
    backend: 8443
