# foninhoiuri-kong/docker-compose.yml
version: '3.8'

services:
  # O serviço 'kong-database' foi removido, pois o Kong usará um PostgreSQL existente.
  # O serviço 'db-setup' também foi removido conforme sua solicitação.
  #
  # Lembre-se: O banco de dados 'kong' DEVE ser criado manualmente no seu PostgreSQL existente.
  # Conecte-se ao seu PostgreSQL (host: postgresql, user: default, password: default) e execute:
  # CREATE DATABASE kong;

  # Serviço para executar as migrações do Kong
  kong-migrations:
    image: kong:latest
    command: >
      sh -c "
        echo 'Aguardando o PostgreSQL estar saudável para migrações...';
        sleep 10; # Dá um tempo extra para o PostgreSQL estar totalmente pronto
        # Usando credenciais 'default' e host 'postgresql'
        KONG_DATABASE=postgres KONG_PG_HOST=postgresql KONG_PG_USER=default KONG_PG_PASSWORD=default KONG_PG_DATABASE=kong kong migrations bootstrap;
      "
    # A dependência de 'db-setup' foi removida, pois 'db-setup' também foi removido.
    restart: "no"

  kong:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      kong-migrations: # O Kong principal só inicia após as migrações terem sido concluídas
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql # Ajustado para o nome do contêiner PostgreSQL existente
      KONG_PG_USER: default   # Ajustado para 'default' conforme docker-compose do seu PostgreSQL
      KONG_PG_PASSWORD: default # Ajustado para 'default' conforme docker-compose do seu PostgreSQL
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000,0.0.0.0:8443 ssl
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
