# foninhoiuri-kong/docker-compose.yml
version: '3.8'

services:
  # O serviço 'kong-database' foi removido, pois o Kong usará um PostgreSQL existente.
  # O nome do seu PostgreSQL existente no Umbrel é 'foninhoiuri-postgresql'.

  # Serviço auxiliar para garantir que o banco de dados 'kong' exista no PostgreSQL externo
  db-setup:
    image: postgres:latest # Usamos uma imagem postgres para ter o cliente psql
    command: >
      sh -c "
        echo 'Aguardando o PostgreSQL estar saudável para criar o banco de dados...';
        sleep 10; # Dá um tempo extra para o PostgreSQL estar totalmente pronto
        # Usando credenciais padrão do PostgreSQL ('postgres'/'postgres') e host 'foninhoiuri-postgresql'
        PGPASSWORD=postgres psql -h foninhoiuri-postgresql -U postgres -d postgres -tc 'SELECT 1 FROM pg_database WHERE datname = ''kong''' | grep -q 1 && echo 'Banco de dados kong já existe.' || PGPASSWORD=postgres psql -h foninhoiuri-postgresql -U postgres -d postgres -c 'CREATE DATABASE kong ENCODING UTF8 LC_COLLATE ''C'' LC_CTYPE ''C'' TEMPLATE template0;';
        echo 'Verificação/Criação do banco de dados kong concluída.';
      "
    restart: "no" # Roda apenas uma vez com sucesso e depois sai

  # Serviço para executar as migrações do Kong
  kong-migrations:
    image: kong:latest
    command: >
      sh -c "
        echo 'Iniciando as migrações do Kong...';
        # Usando credenciais padrão do PostgreSQL ('postgres'/'postgres') e host 'foninhoiuri-postgresql'
        KONG_DATABASE=postgres KONG_PG_HOST=foninhoiuri-postgresql KONG_PG_USER=postgres KONG_PG_PASSWORD=postgres KONG_PG_DATABASE=kong kong migrations bootstrap;
      "
    depends_on:
      db-setup: # Depende que o banco de dados 'kong' tenha sido criado
        condition: service_completed_successfully
    restart: "no"

  kong:
    image: kong:latest
    restart: unless-stopped
    depends_on:
      kong-migrations: # O Kong principal só inicia após as migrações terem sido concluídas
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: foninhoiuri-postgresql # Host do seu PostgreSQL existente no Umbrel
      KONG_PG_USER: default # Usuário padrão do PostgreSQL (assumindo 'default' = 'postgres')
      KONG_PG_PASSWORD: default # Senha padrão do PostgreSQL (assumindo 'default' = 'postgres')
      KONG_PG_DATABASE: kong # Nome do banco de dados para o Kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001,0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000,0.0.0.0:8443 ssl
    ports:
      - "8000:8000/tcp"
      - "8443:8443/tcp"
      - "8001:8001/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
