version: '3.7'

services:
  # ----------------------------------------------------
  # 1. Serviço Web Principal (Servidor Front-end)
  # ----------------------------------------------------
  web:
    image: chatwoot/chatwoot:v3.10.0 # Utilize a versão estável mais recente
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    # O comando inicia o servidor Rails na porta 3000
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    ports:
      - 3000:3000 # Porta interna que o Umbrel usará para o proxy
    volumes:
      - chatwoot_storage:/app/storage # Volume para armazenamento de arquivos
    environment:
      # Variáveis de Ambiente Essenciais para Produção
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      - FRONTEND_URL=http://chatwoot.local:3000 # O Umbrel fará o proxy reverso
      - FORCE_SSL=false 
      
      # Variável Secreta (Chave de Segurança)
      - SECRET_KEY_BASE=$APP_SECRET_CHATWOOT_SECRET_KEY_BASE
      
      # Configuração do Banco de Dados
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=chatwoot
      - POSTGRES_PASSWORD=$APP_SECRET_CHATWOOT_POSTGRES_PASSWORD
      - POSTGRES_DATABASE=chatwoot
      
      # Configuração do Redis
      - REDIS_URL=redis://redis:6379/1
      
      # Configuração de Email (ESSENCIAL para redefinição de senha e convites)
      # Remova o comentário e preencha com seu servidor SMTP real
      # - MAILER_SENDER_EMAIL=chatwoot@$UMBREL_WEB_DOMAIN
      # - SMTP_ADDRESS=
      # - SMTP_USERNAME=
      # - SMTP_PASSWORD=
      
  # ----------------------------------------------------
  # 2. Serviço Worker (Sidekiq para tarefas em segundo plano)
  # ----------------------------------------------------
  worker:
    image: chatwoot/chatwoot:v3.10.0
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    # O comando inicia o worker Sidekiq
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    volumes:
      - chatwoot_storage:/app/storage
    environment:
      # Repete as configurações essenciais
      - RAILS_ENV=production
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=$APP_SECRET_CHATWOOT_SECRET_KEY_BASE
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=$APP_SECRET_CHATWOOT_POSTGRES_PASSWORD
      - POSTGRES_USERNAME=chatwoot
      - POSTGRES_DATABASE=chatwoot
      - REDIS_URL=redis://redis:6379/1

