services:
  chatwoot:
    image: chatwoot/chatwoot:v4.6.0-ce
    container_name: chatwoot_web
    restart: unless-stopped
    environment:
      # Configurações Essenciais
      - NODE_ENV=production
      - FRONTEND_URL=http://umbrel.local:3000 
      - FORCE_SSL=false 

      # Variável Secreta (Gerada pelo Umbrel)
      - SECRET_KEY_BASE=pRVuIMatO4Le0L3xsihHl5Zl0yINlHXAYW2QhuzgxtWRrf0lGQfdX9zQ61xx5k1f

      # Configuração do Banco de Dados POSTGRESQL
      - POSTGRES_HOST=postgresql         # mesmo nome definido em container_name
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DATABASE=chatwoot

      # Configuração do Redis
      - REDIS_URL=redis://foninhoiuri-redis:6379/0   # mesmo nome do container

    ports:
      - "3000:3000"

    volumes:
      - ${APP_DATA_DIR}/data/chatwoot/storage:/app/storage
