services:
  chatwoot:
    image: chatwoot/chatwoot:v4.6.0-ce
    container_name: chatwoot_web
    restart: unless-stopped
    environment:
      # Configurações Essenciais
      #- RAILS_ENV=production
      - NODE_ENV=production
      #- INSTALLATION_ENV=docker
      - FRONTEND_URL=http://umbrel.local:3000 
      - FORCE_SSL=false 
      
      # Variável Secreta (Gerada pelo Umbrel)
      - SECRET_KEY_BASE=pRVuIMatO4Le0L3xsihHl5Zl0yINlHXAYW2QhuzgxtWRrf0lGQfdX9zQ61xx5k1f
      
      # Configuração do Banco de Dados POSTGRESQL (Compartilhado)
      - POSTGRES_HOST=postgres       # Nome do serviço do seu foninhoiuri-postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=default    # Usuário fixo conforme Evolution API
      - POSTGRES_PASSWORD=default    # Senha fixa conforme Evolution API
      - POSTGRES_DATABASE=chatwoot   # Novo database exclusivo para este app
      
      # Configuração do Redis (Compartilhado)
      - REDIS_URL=redis://redis:6379/chatwoot # Nome do serviço do seu foninhoiuri-redis
	ports:
      - "3000:3000"
	volumes:
      - ${APP_DATA_DIR}/data/chatwoot/storage:/app/storage
