version: '3.7'

services:
  token-generator:
    image: node:20
    container_name: token-generator
    volumes:
      - ${APP_DATA_DIR}/app:/usr/src/app
      - ${APP_DATA_DIR}/data/credenciais.json:/usr/src/app/credenciais.json
    working_dir: /usr/src/app
    command: bash -c "npm install express google-auth-library && node index.js"
    ports:
      - 3000:3000
    restart: unless-stopped
