version: '3.8'
services:
  app_proxy:
    environment:
      APP_HOST: token-generator
      APP_PORT: 3000
    container_name: token-generator_app_proxy_1

  token-generator:
    image: node:20
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/credenciais.json:/usr/src/app/credenciais.json
      - ${APP_DATA_DIR}/app:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install express google-auth-library && node index.js"
    environment:
      - TZ=America/Sao_Paulo
    container_name: token-generator_server_1
