version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"

  web:
    image: artibex/piper-http:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/models:/app/models # Para persistir os modelos baixados
    ports:
      - "5000:5000" # Mapeia a porta 5000 do host para a porta 5000 do contêiner
    environment:
      # Exemplo de download de um modelo específico do Hugging Face.
      # Você pode alterar esta URL para o modelo que desejar.
      # Consulte https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0
      MODEL_DOWNLOAD_LINK: https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/kusal/medium/en_US-kusal-medium.onnx?download=true
      # Argumentos adicionais para o servidor HTTP do Piper, se necessário.
      # Baseado no http_server.py do seu projeto
      # PIPER_ARGS: "--speaker 0 --length-scale 1.0 --noise-scale 0.667 --noise-w 0.8"
