services:
  redisinsight:
    container_name: redisinsight # <--- AJUSTADO: Consistente com o ID do seu app
    image: redis/redisinsight:latest # Imagem oficial do RedisInsight
    restart: unless-stopped # <--- AJUSTADO: Padrão do Umbrel (mais robusto que on-failure)
    ports:
      - "5540:5540" # Porta da interface web, correspondendo ao umbrel-app.yml
    volumes:
      - ${APP_DATA_DIR}/data:/db
    environment:
      RI_REDIS_URL: "redis://redis:6379" # <--- CORRIGIDO: O nome do serviço do seu Redis é 'redis'
