version: '3.8'
services:
  app_proxy:
    environment:
      APP_HOST: n8n-plus_server_1
      APP_PORT: 5678
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    container_name: n8n_app_proxy_1
  server:
    image: n8nio/n8n:1.99.1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - N8N_HOST=$DEVICE_DOMAIN_NAME
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_TUNNEL_URL=https://n8n.igoriurialves.com.br
      - TZ=America/Sao_Paulo
    container_name: n8n-plus_server_1
