version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: n8n_plus_server_1
      APP_PORT: 5465
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    container_name: n8n_plus_app_proxy_1
  server:
    image: >-
      n8nio/n8n:1.113.2
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    ports:
      - 5465:5465
    environment:
      - PUID=1000
      - PGID=1000
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.igoriurialves.com.br
      - WEBHOOK_URL=https://n8n.igoriurialves.com.br
      - N8N_EDITOR_BASE_URL=https://n8n.igoriurialves.com.br
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.igoriurialves.com.br
      - N8N_PORT=5465
      - WEBHOOK_URL=https://n8n.igoriurialves.com.br
      - N8N_EDITOR_BASE_URL=https://n8n.igoriurialves.com.br
      - N8N_SECURE_COOKIE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_EXPERIMENTAL_FEATURES=python
    container_name: n8n_plus_server_1
