version: '3.8'
services:
  app_proxy:
    environment:
      APP_HOST: n8n_plus_server_1
      APP_PORT: 5679
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    container_name: n8n_plus_app_proxy_1
  server:
    image: >-
      n8nio/n8n:1.102.3@sha256:14525d353ead198a066b55c1e592f23355d5dcb06f1bacb831a3b82d68426fa0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      
      - N8N_PROTOCOL=https
      - N8N_HOST=nn.igoriurialves.com.br
      - N8N_PORT=5679
      - WEBHOOK_URL=https://nn.igoriurialves.com.br
      - N8N_EDITOR_BASE_URL=https://nn.igoriurialves.com.br
      - N8N_SECURE_COOKIE=false
      
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    container_name: n8n_plus_server_1
