version: '3.7'

services:
  maybe:
    container_name: maybe_app
    image: ghcr.io/maybe-finance/maybe:latest
    ports:
      - "6260:6260" 
    environment:
      - SECRET_KEY_BASE=712ac7624abad6ec987b1678f67c8ecbff06ddb8bbecae1451a82e4ae0190387141829adad9b77826f7c93a4a33fafc8ecb462d922dbf08eef1d6a37f7a530e2
      - DATABASE_URL=postgresql://default:default@postgres:5432/maybe_production
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - HOST=umbrel.local
      - PORT=6260
      - RAILS_FORCE_SSL=false
      - RAILS_ASSUME_SSL=false
      - PUID=1026
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure
