version: '3.9'
services:
  app_proxy:
    container_name: redis_proxy_1
    depends_on:
      - server
    environment:
      APP_HOST: redis_db_1
      APP_PORT: 6379        
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      PROXY_TARGET: http://${DEVICE_DOMAIN_NAME}
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  server:
    container_name: redis_db_1
    image: redis:latest
    platform: linux/amd64      # Compatibilidade Umbrel
    restart: always
    command: redis-server /bin/sh -c "echo 'App proxy started' && sleep infinity" 
    volumes:
      - ${APP_DATA_DIR}/data:/data # Persistência de dados
      - ${APP_DATA_DIR}/data:/usr/local/etc/redis/redis.conf 
      # - ${APP_DATA_DIR}/logs:/var/log/redis  # Caso queira logs persistentes (opcional)
    ports:
      - "6380:6379"            # Expõe a porta para acesso externo (ajuste se necessário)
