version: '3.7'

services:
  app_proxy:
    container_name: app_proxy_1
    depends_on:
      - server
    environment:
      APP_HOST: redis_db_1
      APP_PORT: 6379        
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      PROXY_TARGET: http://${DEVICE_DOMAIN_NAME}
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    volumes:
      - ./proxy:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "proxy.js"]

  server:
    container_name: redis_db_1
    image: redis:8.0
    platform: linux/amd64      # Compatibilidade Umbrel
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data:/data     # Persistência de dados
      # - ${APP_DATA_DIR}/logs:/var/log/redis  # Caso queira logs persistentes (opcional)
    ports:
      - "6379:6379"            # Expõe a porta para acesso externo (ajuste se necessário)
