version: '4.0'

services:
  app_proxy:
    container_name: redis_proxy_1
    depends_on:
      - server
    environment:
      APP_HOST: redis_server_1
      APP_PORT: 6379
    image: redis:latest

  redisinsight:
    image: redis/redisinsight:latest
    restart: on-failure
    ports:
      - "5540:5540"
    volumes:
      - ${APP_DATA_DIR}/redisinsight/data:/data
      - ${APP_DATA_DIR}/redisinsight/logs:/data/logs
    depends_on:
      - server

  server:
    container_name: redis_server_1
    image: redis:latest
    platform: linux/amd64
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
