version: '3.9'

services:
  app_proxy:
    container_name: redis_proxy_1
    image: >-
    git@github.com:redis/redis.git
    depends_on:
      - server
    environment:
      APP_HOST: redis_db_1
      APP_PORT: 6379        
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      PROXY_TARGET: http://${DEVICE_DOMAIN_NAME}
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    image: your-proxy-image # Defina a imagem correta aqui
    # Remover o comando `redis-server`, não faz sentido nesse container
    # command: redis-server ...

  server:
    container_name: redis_db_1
    image: redis:latest
    platform: linux/amd64
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
