# Removido 'version: "3.8"' para evitar o warning 'the attribute `version` is obsolete'
# O Docker Compose V2 não precisa mais da chave 'version'.

services:
  redis:
    image: redis:latest # Imagem oficial do Redis do Docker Hub
    container_name: foninhoiuri-redis # Nome específico para o contêiner do seu app Redis
    restart: unless-stopped # Garante que o contêiner reinicie automaticamente
    # ports: # <--- LINHA DE EXPOSIÇÃO DE PORTA COMENTADA/REMOVIDA
    #   - "6379:6379" # Não é necessário expor para o host se o Redis for usado apenas internamente por outros apps no Umbrel.
    volumes:
      - ${APP_DATA_DIR}/data:/data # Volume persistente para os dados do Redis
      # Se você tiver um arquivo redis.conf personalizado na raiz da sua pasta do app:
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    # Se você usar um redis.conf personalizado, adicione esta linha para que o Redis o utilize:
    # command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck: # Adicionado healthcheck para garantir que o Redis esteja realmente pronto
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s # Verifica a cada 5 segundos
      timeout: 5s # Tempo limite para a verificação
      retries: 5 # Tenta 5 vezes antes de considerar falha
      start_period: 60s # Período inicial para o contêiner se aquecer antes de começar as verificações
