version: '3.9'

services:
  app_proxy:
    container_name: redis_proxy_1
    depends_on:
      - server
    environment:
      APP_HOST: redis_db_1
      APP_PORT: 62541       
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      PROXY_TARGET: http://${DEVICE_DOMAIN_NAME}
      PROXY_AUTH_WHITELIST: /webhook-test/*,/webhook/*
    image: redis:latest

  server:
    container_name: redis_db_1
    image: redis:latest
    platform: linux/amd64
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data:/usr/local/etc/redis/redis.conf
    ports:
      - 62541
     # - "6380:6379"
