version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: redis_db_1       # Nome do container definido abaixo
      APP_PORT: 6379             # Porta padrão do Redis
    container_name: redis_db_proxy_1

  server:
    image: redis:8.0
    platform: linux/amd64       # Para garantir compatibilidade com o Umbrel
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data:/data   # Volume correto para persistência de dados Redis
    container_name: redis_db_1
