services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: default # Variável de ambiente para o usuário do banco de dados
      POSTGRES_PASSWORD: default # Variável de ambiente para a senha do banco de dados (Altamente recomendado ALTERAR!)
      #POSTGRES_DB: default # Variável de ambiente para o nome do banco de dados padrão
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/postgresql/data
