version: '3.8'

services:
  evolutionapi:
    image: atendai/evolution-api:latest
    container_name: evolutionapi
    ports:
      - "8080:8080" # Assumindo que a API roda na porta 8080
    environment:
      # Estas são exemplos baseados no arquivo .env.example
      # Você deve personalizá-los com seus valores reais
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - SENTRY_DSN=
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - EVENT_EMITTER_MAX_LISTENERS=50
      - DEL_INSTANCE=false
      - DATABASE_PROVIDER=postgresql
      - AUTHENTICATION_API_KEY:Kg6Y4qPs57qF6J2kBe5imZVJAlCMnURwv
      - DATABASE_CONNECTION=postgresql://evolution:evolution@postgres:5432/evolutionapi # Usuário e Senha alterados
    volumes:
      # Se você precisar de armazenamento persistente para qualquer dado (ex: sessões, mídia)
      # Descomente e ajuste estas linhas
      - ${APP_DATA_DIR}/data/evolutionapi:/app/data # Exemplo para um volume de dados
    depends_on:
      - postgres
    restart: unless-stopped

  postgres: # NOME DO SERVIÇO: postgres
    image: postgres:13-alpine
    container_name: evolutionapi_db
    environment:
      POSTGRES_DB: evolutionapi
      POSTGRES_USER: evolution # Usuário alterado
      POSTGRES_PASSWORD: evolution # Senha alterada
    volumes:
      - ${APP_DATA_DIR}/datapostgres_data:/var/lib/postgresql/data # Volume persistente para dados do banco de dados
    expose:
      - "5432"
    restart: unless-stopped

volumes:
  postgres_data: # Volume para dados do PostgreSQL
