services:
  evolution-api:
    image: atendai/evolution-api:latest # Considere usar uma versão específica, ex: atendai/evolution-api:1.0.0
    container_name: evolution-api
    ports:
      - "8080:8080" # Porta externa para 80 para compatibilidade com o Umbrel
    environment:
      # Variável de Autenticação ESSENCIAL (injetada pelo Umbrel config)
      AUTHENTICATION_API_KEY: "${AUTHENTICATION_API_KEY}"

      # Configuração para Habilitar WebSockets
      WEBSOCKET_ENABLED: "true"

      # As configurações do Redis foram removidas, pois o serviço Redis será removido.
      # Se a Evolution API ainda precisar de cache, você precisará configurar uma alternativa ou desabilitar o cache.
      # CACHE_REDIS_ENABLED: "true"
      # CACHE_REDIS_URI: "redis://redis:6379"
      # CACHE_REDIS_PREFIX_KEY: "evolution"
      # CACHE_REDIS_TTL: "604800"
      # CACHE_REDIS_SAVE_INSTANCES: "true"

      # Configurações para o PostgreSQL (como banco de dados principal)
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://evolution:evolution@postgresql:5432/evolution?schema=public"

      SERVER_PORT: "8080"
      SERVER_URL: "http://evolution-api.umbrel.local" # URL para acesso interno no Umbrel
    volumes:
      - ${APP_DATA_DIR}/evolution-api/data:/app/data # Persistência de dados do Evolution API
    depends_on:
      # Redis foi removido das dependências
      - postgresql
    restart: unless-stopped
  #  networks:
   #   - default # Conecta à rede principal do Umbrel

  # O serviço Redis foi completamente removido.

  postgresql:
    image: postgres:13
    container_name: postgresql-evolution-api
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution # Use a mesma senha definida acima!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data
    restart: unless-stopped

# Definição dos volumes nomeados para persistência de dados
volumes:
  # redis_data foi removido.
  postgresql_data:

#networks:
#  default:
 #   external: true
 #   name: umbrel_main_network # Conecta à rede Docker principal do Umbrel
