version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest # Considere usar uma versão específica, ex: atendai/evolution-api:1.0.0
    container_name: evolution-api
    ports:
      - "80:8080" # CORRIGIDO: Porta externa para 80 para compatibilidade com o Umbrel
    environment:
      # Variável de Autenticação ESSENCIAL (idealmente injetada pelo Umbrel config)
      AUTHENTICATION_API_KEY: "${AUTHENTICATION_API_KEY}" # <<--- AQUI DEVERIA SER ${AUTHENTICATION_API_KEY} para ser configurável pelo Umbrel

      # Configuração para Habilitar WebSockets
      WEBSOCKET_ENABLED: "true"

      # Configurações para o Redis (como cache)
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://redis:6379" # O nome do serviço 'redis' resolve para o IP do contêiner Redis
      CACHE_REDIS_PREFIX_KEY: "evolution"
      CACHE_REDIS_TTL: "604800"
      CACHE_REDIS_SAVE_INSTANCES: "true"

      # Configurações para o PostgreSQL (como banco de dados principal)
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      # Usar variável de ambiente para a senha do PostgreSQL
      DATABASE_CONNECTION_URI: "postgresql://evolution:${POSTGRES_PASSWORD}@postgresql:5432/evolution?schema=public" # Mantenha a senha do PostgreSQL consistente!

      SERVER_PORT: "8080"
      SERVER_URL: "http://evolution-api.umbrel.local" # URL para acesso interno no Umbrel
    volumes:
      - ${APP_DATA_DIR}/evolution-api/data:/app/data # Persistência de dados do Evolution API
    depends_on:
      - redis
      - postgresql
    restart: unless-stopped
    networks:
      - default # Conecta à rede principal do Umbrel

  redis:
    image: redis:latest # Considere usar uma versão específica, ex: redis:7.0
    container_name: redis-evolution-api
    volumes:
      - redis_data:/data # Volume nomeado para persistência de dados do Redis (boa prática)
    command: redis-server --appendonly yes # Habilita persistência de dados
    restart: unless-stopped
    networks:
      - default

  postgresql:
    image: postgres:13 # Versão específica, o que é bom!
    container_name: postgresql-evolution-api
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use uma variável de ambiente para a senha
      PGDATA: /var/lib/postgresql/data/pgdata # Caminho para os dados dentro do contêiner
    volumes:
      - postgresql_data:/var/lib/postgresql/data # Volume nomeado para persistência de dados do PostgreSQL
    restart: unless-stopped
    networks:
      - default

# Definição dos volumes nomeados para persistência de dados
volumes:
  redis_data:
  postgresql_data:

networks:
  default:
    external:
      name: umbrel_main_network # Conecta à rede Docker principal do Umbrel
