version: '3.8'

services:
  evolution_api:
    image: atendai/evolution-api:latest # Mantemos :latest para pegar a versão mais nova
    container_name: evolution_api_instance
    restart: on-failure
    environment:
      - AUTHENTICATION_ENABLED=true
      - AUTHENTICATION_API_KEY=wBSKDHYiz1vqMAHQBxOW74zHLogqIqcL # Mantenha a sua AUTHENTICATION_API_KEY
      
      # REDIS CONFIGS (Mantidas)
      - REDIS_URI=redis://redis:6379/0
      - CACHE_DRIVER=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URL=redis://redis:6379/0

      # OUTRAS VARS (Mantidas)
      - DATABASE_CONNECTION_URI=postgresql://user:senha_complexa_e_segura@postgres:5432/evolution
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - LOG_BAILEYS=trace
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET,REDIS,BAILEYS
      - LOG_COLOR=true
      - SERVER_URL=http://${DEVICE_DOMAIN_NAME}
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    volumes:
      - ${APP_DATA_DIR}/evolution_store:/evolution/store
      - ${APP_DATA_DIR}/evolution_instances:/evolution/instances
    depends_on:
      postgres:
        condition: service_healthy # <--- GARANTE QUE O POSTGRES ESTÁ SAUDÁVEL ANTES DE INICIAR A API
      redis:
        condition: service_healthy # <--- GARANTE QUE O REDIS ESTÁ SAUDÁVEL ANTES DE INICIAR A API 

  postgres:
    image: postgres:latest
    container_name: evolution_postgres
    platform: linux/amd64
    environment:
      # **CORRIGIDO: CREDENCIAIS E BANCO DE DADOS PADRONIZADOS**
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha_complexa_e_segura
      POSTGRES_DB: evolution
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
      - ${APP_DATA_DIR}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck: # <--- DEFINIÇÃO DO HEALTHCHECK PARA O POSTGRES
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s # Tempo para o serviço iniciar antes de começar a checar

  redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${APP_DATA_DIR}/redisdata:/data
    healthcheck: # <--- DEFINIÇÃO DO HEALTHCHECK PARA O REDIS
      test: ["CMD", "redis-cli", "ping"] # Comando para verificar a saúde do Redis
      interval: 5s # Intervalo entre as verificações (5 segundos)
      timeout: 5s # Tempo limite para o comando de verificação (5 segundos)
      retries: 5 # Número de tentativas antes de considerar o serviço como "não saudável"
      start_period: 20s # Tempo para o serviço iniciar antes de começar a checar
