version: "3.8"

services:
  app_proxy:
    container_name: evolution_proxy
    depends_on:
      - api
    environment:
      APP_HOST: evolution_api
      APP_PORT: 8080
    image: atendai/evolution-api:v2.2.3
    restart: always
    ports:
      - "8080:8080"

  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.3
    restart: always
    environment:
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      REDIS_URL: ${REDIS_URL}
    expose:
      - "8080"
    depends_on:
      - postgresql

  postgresql:
    container_name: evolution_postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - evolution-pg-data:/var/lib/postgresql/data

volumes:
  evolution-pg-data:
