version: '3.8'

services:
  evolutionapi:
    image: atendai/evolution-api:latest
    container_name: evolutionapi
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - SENTRY_DSN=
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - EVENT_EMITTER_MAX_LISTENERS=50
      - DEL_INSTANCE=false
      - DATABASE_PROVIDER=postgresql
      # A string de conexão da API agora aponta para o usuário 'user' com a senha 'evolution'
      - DATABASE_CONNECTION=postgresql://user:evolution@postgres:5432/evolutionapi
      - DATABASE_URL=postgresql://user:evolution@postgres:5432/evolutionapi
      - TZ=America/Sao_Paulo
      - AUTHENTICATION_API_KEY=Kg6Y4qPs57qF6J2kBe5imZVJAlCMnURwv
    volumes:
      - ${APP_DATA_DIR}/foninhoiuri-evolution-api/data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    container_name: evolutionapi_db
    environment:
      POSTGRES_DB: evolutionapi
      POSTGRES_USER: user # <-- O usuário do banco de dados será 'user'
      POSTGRES_PASSWORD: evolution # <-- A senha do banco de dados será 'evolution'
      TZ: America/Sao_Paulo
    volumes:
      - ${APP_DATA_DIR}/foninhoiuri-evolution-api/postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped
