version: '3.8'

services:
  app_proxy:
    image: atendai/evolution-api:latest
    container_name: evolution_proxy
    restart: always
    environment:
      APP_HOST: evolution_api
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
      AUTHENTICATION_API_KEY: 63FvHHwNfjMzaj8UStNc96UTGQ94CRHY
      # Manter essas variáveis para o proxy, caso a imagem base espere.
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: postgresql://default:default@postgres:5432/default
      CACHE_REDIS_ENABLED: "true" # <--- ADICIONADO: Habilita o cache Redis
      CACHE_REDIS_URI: "redis://redis:6379/0" # <--- ADICIONADO: URI de conexão do Redis
    ports:
      - "8080:8080"
    command: ["npm", "run", "start:prod"] # Mantido: Tenta forçar o proxy a iniciar sem rodar migrações
    depends_on:
      evolution_api:
        condition: service_started
      postgres:
        condition: service_healthy
      redis: # <--- ADICIONADO: Dependência do serviço Redis
        condition: service_started # O proxy só precisa que o Redis tenha iniciado

  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_instance
    restart: on-failure
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://default:default@postgres:5432/default
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evo
      - DATABASE_SAVE_DATA_INSTANCE=false
      - DATABASE_SAVE_DATA_NEW_MESSAGE=false
      - DATABASE_SAVE_MESSAGE_UPDATE=false
      - DATABASE_SAVE_DATA_CONTACTS=false
      - DATABASE_SAVE_DATA_CHATS=false
      - CACHE_REDIS_ENABLED=true # <--- ADICIONADO: Habilita o cache Redis
      - CACHE_REDIS_URI=redis://redis:6379/0 # <--- ADICIONADO: URI de conexão do Redis
    volumes:
      - ${APP_DATA_DIR}/data/evolution-api/store:/evolution/store
      - ${APP_DATA_DIR}/data/evolution-api/instances:/evolution/instances
    depends_on:
      postgres:
        condition: service_healthy
      redis: # <--- ADICIONADO: Dependência do serviço Redis
        condition: service_started # A API só precisa que o Redis tenha iniciado

  postgres:
    image: postgres:latest
    container_name: evolution_postgres
    # ATENÇÃO: Ajuste a plataforma conforme a arquitetura do seu Umbrel OS (linux/arm64 para Raspberry Pi, por exemplo).
    # Se o seu Umbrel for ARM64, mude para: platform: linux/arm64
    platform: linux/amd64
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis: # <--- NOVO SERVIÇO: Redis
    image: redis:latest # Imagem oficial do Redis
    container_name: evolution_redis # Nome amigável para o contêiner Redis
    restart: always # Garante que o Redis sempre tente reiniciar
    ports:
      - "6379:6379" # Opcional: expõe a porta do Redis para acesso externo (útil para ferramentas de administração)
    volumes:
      - ${APP_DATA_DIR}/redisdata:/data # Persiste os dados do Redis
    healthcheck: # Adiciona uma verificação de saúde para o Redis
      test: ["CMD", "redis-cli", "ping"] # Verifica se o Redis está respondendo
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
