version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.2.3
    container_name: evolution-api
    ports:
      - "8080:8080" # Porta externa:Porta interna do contêiner
    environment:
      # Configurações para o Redis (como cache)
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://redis:6379/0" # 'redis' é o nome do serviço Redis no Docker Compose
      CACHE_REDIS_PREFIX_KEY: "evolution"
      CACHE_REDIS_TTL: "604800"
      CACHE_REDIS_SAVE_INSTANCES: "true"

      # Configurações para o PostgreSQL (como banco de dados principal)
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      # Conexão com o serviço 'postgresql' definido abaixo.
      # ATENÇÃO: Altere 'your_postgres_password' para uma senha forte e segura!
      DATABASE_CONNECTION_URI: "postgresql://evolution:your_postgres_password@postgresql:5432/evolution?schema=public"

      SERVER_PORT: "8080"
      SERVER_URL: "http://evolution-api.umbrel.local" # URL para acesso interno no Umbrel
    volumes:
      - ${APP_DATA_DIR}/evolution-api/data:/app/data # Persistência de dados do Evolution API
    depends_on:
      - redis
      - postgresql # Adicione a dependência no PostgreSQL
    restart: unless-stopped

  # Este é o serviço Redis que você já tem instalado como app no seu Umbrel
  # Não é necessário definir um novo serviço Redis aqui se ele já está rodando como um app Umbrel separado
  # e você está apenas referenciando-o via nome de serviço (o que o Umbrel faz automaticamente).
  # No entanto, se o Redis não for um app separado do Umbrel e você quiser ele acoplado a este app,
  # MANTENHA este bloco. Se ele for um app *separado* e *instalado*, você pode remover este bloco de 'redis'.
  # Por enquanto, vou mantê-lo, assumindo que ele pode ser um container separado gerenciado por este compose.
  redis:
    image: redis:latest
    container_name: redis-evolution-api
    volumes:
      - ${APP_DATA_DIR}/redis:/data # Persistência de dados do Redis
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgresql:
    image: postgres:13 # Versão recomendada para compatibilidade e estabilidade
    container_name: postgresql-evolution-api
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: "your_postgres_password" # ATENÇÃO: Altere para uma senha forte e segura!
      PGDATA: /var/lib/postgresql/data/pgdata # Caminho para os dados do PostgreSQL
    volumes:
      - ${APP_DATA_DIR}/postgresql:/var/lib/postgresql/data # Persistência dos dados do PostgreSQL
    restart: unless-stopped
