version: '3.8'

services:
  evolution_api:
    image: atendai/evolution-api:latest # Mantemos :latest para pegar a versão mais nova
    container_name: evolution_api_instance
    restart: on-failure
    environment:
      - AUTHENTICATION_ENABLED=true
      - AUTHENTICATION_API_KEY=wBSKDHYiz1vqMAHQBxOW74zHLogqIqcL # Mantenha a sua AUTHENTICATION_API_KEY

      # **IMPORTANTE: REMOVA OU COMENTE AS LINHAS ABAIXO NO SEU docker-compose.yml**
      # - DATABASE_CONNECTION_URI=postgresql://default:default@postgres:5432/default
      # - DATABASE_CONNECTION_URL=postgresql://default:default@postgres:5432/default
      # **Isso garante que a DATABASE_URL seja lida APENAS do .env**

      # REDIS CONFIGS (Mantidas)
      - REDIS_URL=redis://redis:6379/0
      - CACHE_DRIVER=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URL=redis://redis:6379/0

      # OUTRAS VARS (Mantidas)
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - LOG_BAILEYS=trace
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
      - LOG_COLOR=true
      - SERVER_URL=http://${DEVICE_DOMAIN_NAME}
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    env_file: # Esta linha é crucial!
      - ${APP_DATA_DIR}/.env
    volumes:
      - ${APP_DATA_DIR}/evolution_store:/evolution/store
      - ${APP_DATA_DIR}/evolution_instances:/evolution/instances
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 

  postgres:
    image: postgres:latest
    container_name: evolution_postgres
    platform: linux/amd64
    environment:
      # **CORRIGIDO: CREDENCIAIS E BANCO DE DADOS PADRONIZADOS**
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: evolution
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${APP_DATA_DIR}/redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
