services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    environment:
      DATABASE_SAVE_DATA_INSTANCE: true
      LOG_BAILEYS: trace
      LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS
      
    ports:
      - "8080:8080"
    env_file:
      - ${APP_DATA_DIR}/.env
    volumes:
      - ${APP_DATA_DIR}/evolution_store:/evolution/store
      - ${APP_DATA_DIR}/evolution_instances:/evolution/instances
