version: '3.8'

services:
  app_proxy:
    image: atendai/evolution-api:latest
    environment:
      APP_HOST: evolution_api
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
      AUTHENTICATION_API_KEY: 63FvHHwNfjMzaj8UStNc96UTGQ94CRHY
    depends_on:
      - evolution_api

  evolution_api:
    image: atendai/evolution-api:latest
    restart: on-failure
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://default:default@postgres:5432/default
      - DATABASE_CONNECTION_DB_PREFIX_NAME=evo
      - DATABASE_SAVE_DATA_INSTANCE=false
      - DATABASE_SAVE_DATA_NEW_MESSAGE=false
      - DATABASE_SAVE_MESSAGE_UPDATE=false
      - DATABASE_SAVE_DATA_CONTACTS=false
      - DATABASE_SAVE_DATA_CHATS=false
    volumes:
      - ${APP_DATA_DIR}/data/evolution-api/store:/evolution/store
      - ${APP_DATA_DIR}/data/evolution-api/instances:/evolution/instances
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    platform: linux/amd64 # Manter para garantir compatibilidade se o umbrelOS estiver em uma arquitetura específica
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    # A porta 5432 será acessível internamente dentro da rede Docker.
    # O umbrelOS fará o mapeamento de portas externas se necessário via umbrel-app.yml.
    ports:
      - "5432:5432" # Mapeamento interno para o contêiner. Umbrel irá gerenciar o acesso externo.
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
