services:
  evolution-api:
    image: foninhoiuri/evolution-api:v2.2.3
    restart: always
    environment:
      - AUTHENTICATION_API_KEY=Kg6Y4qPs57qF6J2kBe5imZVJAlCMnURwv
      - POSTGRES_PASSWORD=evolution
      - DATABASE_PROVIDER=postgresql
      - DATABASE_URL=postgresql://evolution:evolution@postgresql:5432/evolution
    ports:
      - "8080:8080"  # Alterado para evitar conflito com a porta 80 global
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=evolution
    volumes:
      - evolution-pg-data:/var/lib/postgresql/data

volumes:
  evolution-pg-data:
