version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: evolution-api  # Corrigido aqui
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
      AUTHENTICATION_API_KEY: 63FvHHwNfjMzaj8UStNc96UTGQ94CRHY

  evolution-api:
    image: atendai/evolution-api:latest
    user: "1000:1000"
    restart: on-failure
    environment:
      - DATABASE_PROVIDER=postgresql # Ou postgresql, mysql
    volumes:
      - ${APP_DATA_DIR}/data/evolution-api/store:/evolution/store
      - ${APP_DATA_DIR}/data/evolution-api/instances:/evolution/instances
