version: '3.9'

services:
  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_instance
    restart: on-failure
    environment:
      - AUTHENTICATION_ENABLED=true
      - AUTHENTICATION_API_KEY=wBSKDHYiz1vqMAHQBxOW74zHLogqIqcL
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1020885143

      # Nenhuma configuração de Redis aqui

      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_CONNECTION_URI=postgresql://default:default@postgres:5432/default

      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET,BAILEYS # Removido REDIS
      - LOG_COLOR=true
      - LOG_BAILEYS=trace
      - SERVER_URL=http://${DEVICE_DOMAIN_NAME}
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    volumes:
      - ${APP_DATA_DIR}/data/evolution-api/store:/evolution/store
      - ${APP_DATA_DIR}/data/evolution-api/instances:/evolution/instances
    depends_on:
      postgres:
        condition: service_healthy # Agora depende apenas do PostgreSQL

  postgres:
    image: postgres:latest
    container_name: evolution_postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - ${APP_DATA_DIR}/data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
