services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "80:8080" # Porta externa deve ser 80 para Umbrel
    environment:
      # Chave de autenticação injetada via umbrel-app.yml
      AUTHENTICATION_API_KEY: "${AUTHENTICATION_API_KEY}"

      # WebSockets habilitados
      WEBSOCKET_ENABLED: "true"

      # Cache Redis desabilitado (não utilizado)
      CACHE_REDIS_ENABLED: "false"

      # Configuração do PostgreSQL
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://evolution:${POSTGRES_PASSWORD}@postgresql:5432/evolution?schema=public"

      # Configurações do servidor
      SERVER_PORT: "8080"
      SERVER_URL: "http://evolution-api.umbrel.local"

    volumes:
      - ${APP_DATA_DIR}/evolution-api/data:/app/data

    depends_on:
      - postgresql

    restart: unless-stopped

    networks:
      - default

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgresql:
    image: postgres:13
    container_name: postgresql-evolution-api
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - postgresql_data:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - default

volumes:
  postgresql_data:

networks:
  default:
    external: true
    name: umbrel_main_network
