version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: foninhoiuri-evolution-api_web_1
      APP_PORT: 8080

  web:
    image: atendai/evolution-api:v2.2.3
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8080:8080
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME}
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME}
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
      APP_HIDDEN_SERVICE: ${APP_HIDDEN_SERVICE}
      APP_PASSWORD: ${APP_PASSWORD}
      APP_SEED: ${APP_SEED}
      TZ: America/Sao_Paulo
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
