version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolutionapi
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
      - AUTHENTICATION_API_KEY=Kg6Y4qPs57qF6J2kBe5imZVJAlCMnURwv
    volumes:
      # Caminho simplificado: os dados da API irão para ${APP_DATA_DIR}/data
      - ${APP_DATA_DIR}/data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: evolutionapi_postgres
    environment:
      TZ: America/Sao_Paulo
    volumes:
      # Caminho simplificado: os dados do MongoDB irão para ${APP_DATA_DIR}/mongodb_data
      - ${APP_DATA_DIR}/mongodb_data:/data/db
    expose:
      - "5432"
    restart: unless-stopped
