services:
  evolution-api:
    image: foninhoiuri/evolution-api:v2.2.3
    restart: always
    environment:
      - AUTHENTICATION_API_KEY=defaultapikey
      - POSTGRES_PASSWORD=examplepassword
    ports:
      - "8080:8080"  # Alterado para evitar conflito com a porta 80 global
    depends_on:
      - postgresql
    networks:
      - default

  postgresql:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=examplepassword
    volumes:
      - evolution-pg-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  evolution-pg-data:

networks:
  default:
    external: true
    name: umbrel-app-network
