version: "3.8"

services:
  app_proxy:
    container_name: evolution_proxy
    depends_on:
      - api
    environment:
      APP_HOST: evolution_api
      APP_PORT: 8080
    image: atendai/evolution-api:v2.2.3
    restart: always
    ports:
      - "8080:8080"

  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.3
    restart: always
    environment:
      - AUTHENTICATION_API_KEY=${E_AUTHENTICATION_API_KEY}
      - POSTGRES_PASSWORD=${E_POSTGRES_PASSWORD}
      - DATABASE_PROVIDER=postgresql
      - DATABASE_URL=postgresql://${E_POSTGRES_USER}:${E_POSTGRES_PASSWORD}@postgresql:5432/${E_POSTGRES_DB}
    expose:
      - "8080"
    depends_on:
      - postgresql

  postgresql:
    container_name: evolution_postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=${E_POSTGRES_DB}
      - POSTGRES_USER=${E_POSTGRES_USER}
      - POSTGRES_PASSWORD=${E_POSTGRES_PASSWORD}
    volumes:
      - evolution-pg-data:/var/lib/postgresql/data

volumes:
  evolution-pg-data:
