services:
  evolution_api:
    image: atendai/evolution-api:latest
    container_name: evolution_api_instance
    restart: unless-stopped # Usar 'unless-stopped' é geralmente mais robusto
    environment:
      # Variáveis de autenticação
      - AUTHENTICATION_ENABLED=true
      - AUTHENTICATION_API_KEY=wBSKDHYiz1vqMAHQBxOW74zHLogqIqcL # Mantenha esta chave secreta!
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1020885143
      
      # Configurações do Redis (AGORA CONECTA AO APP EXTERNO 'foninhoiuri-redis')
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379 # Conecta-se ao serviço 'redis' do app foninhoiuri-redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_TTL=604800
      - CACHE_REDIS_SAVE_INSTANCES=true
      - CACHE_DRIVER=redis

      # Configurações do Banco de Dados (AGORA CONECTA AO APP EXTERNO 'foninhoiuri-postgresql')
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_CONNECTION_URI=postgresql://default:default@postgres:5432/default # Conecta-se ao serviço 'postgres' do app foninhoiuri-postgresql
      
      # Configurações de Log
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET,REDIS,BAILEYS
      - LOG_COLOR=true
      - LOG_BAILEYS=trace
      - SERVER_URL=http://${DEVICE_DOMAIN_NAME} # Variável fornecida pelo Umbrel
      - TZ=America/Sao_Paulo # Fuso horário

    ports:
      - "8080:8080" # Mapeia a porta da Evolution API para acesso externo
    volumes:
      - ${APP_DATA_DIR}/data/evolution-api/store:/evolution/store # Volume para dados da API
      - ${APP_DATA_DIR}/data/evolution-api/instances:/evolution/instances # Volume para instâncias
