version: '3.8'

services:
  evolution-api: # Serviço principal da aplicação
    image: atendai/evolution-api:latest
    container_name: evolutionapi
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - SENTRY_DSN=
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - EVENT_EMITTER_MAX_LISTENERS=50
      - DEL_INSTANCE=false
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION=postgresql://evolution:evolution@postgres:5432/evolutionapi
      - DATABASE_URL=postgresql://evolution:evolution@postgres:5432/evolutionapi
      - TZ=America/Sao_Paulo
      - AUTHENTICATION_API_KEY=Kg6Y4qPs57qF6J2kBe5imZVJAlCMnURwv
    volumes:
      # MUITO IMPORTANTE: SUBSTITUA 'SEU_CAMINHO_COMPLETO_PARA_O_APP_DATA' PELO CAMINHO REAL NO SEU UMBREL.
      # Exemplo: /home/umbrel/umbrel/app-data/foninhoiuri-evolution-api/data:/app/data
      - SEU_CAMINHO_COMPLETO_PARA_O_APP_DATA/data:/app/data # Volume de dados da aplicação
    depends_on:
      - postgres
    restart: unless-stopped

  postgres: # Serviço do banco de dados PostgreSQL
    image: postgres:13
    container_name: evolutionapi_db
    environment:
      POSTGRES_DB: evolutionapi
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: "evolution"
      TZ: America/Sao_Paulo
    volumes:
      # MUITO IMPORTANTE: SUBSTITUA 'SEU_CAMINHO_COMPLETO_PARA_O_APP_DATA' PELO CAMINHO REAL NO SEU UMBREL.
      # Exemplo: /home/umbrel/umbrel/app-data/foninhoiuri-evolution-api/postgres_data:/var/lib/postgresql/data
      - /home/umbrel/umbrel/app-data/foninhoiuri-evolution-api/postgres_data:/var/lib/postgresql/data # Volume persistente para dados do PostgreSQL
    expose:
      - "5432"
    restart: unless-stopped
