version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: evolution-api_server_1
      APP_PORT: 8080
    image: atendai/evolution-api:v2.2.3
    platform: linux/amd64
    restart: always
    ports:
      - '8080:8080'
    volumes:
      # Se o Evolution API precisar de persistência de dados fora do MongoDB, adicione aqui
      - ${APP_DATA_DIR}/evolution-api-data:/app/data
    environment:
