services:
  youtube_downloader:
    image: python:3.11-slim
    container_name: youtube_downloader_instance
    restart: unless-stopped
    working_dir: /app
    ports:
      - "57342:57342"
    volumes:
      - ${APP_DATA_DIR}/app:/app
      - ${APP_DATA_DIR}/app/downloads:/app/downloads
    command: >
      /bin/sh -c "
      pip install --no-cache-dir flask pytube &&
      python main.py
      "
    environment:
      - TZ=America/Sao_Paulo
