services:
  youtube-api:
    build: .
    container_name: youtube_api
    restart: unless-stopped
    working_dir: /app
    ports:
      - "57342:57342"
    volumes:
      - ${APP_DATA_DIR}/app:/app
      - ${APP_DATA_DIR}/app/downloads:/app/downloads
    environment:
      - TZ=America/Sao_Paulo
